blank_issues_enabled: true
contact_links:
  - name: Чукотские zakupki.gov.ru
    url: https://zakupki.gov.ru
    about: ItA aBoUt
  - name: Чукотские zakupki.gov.ru
    url: https://zakupki.gov.ru
    about: ItA aBoUt
  - name: Чукотские zakupki.gov.ru
    url: https://zakupki.gov.ru
    about: ItA aBoUt